export interface MenuItem {
  id: string;
  name: string;
  nameEn?: string;
  description: string;
  descriptionEn?: string;
  price: number;
  category: string;
  concepto?: "mexican" | "sushi";
  badge?: string;
  badgeEn?: string;
  badgeColor?: string;
  allergens?: string;
  emoji: string;
  image?: string;
  halal?: boolean;
  vegetarian?: boolean;
}

/** Map of Spanish badge text ? English badge text */
export const badgeTranslations: Record<string, string> = {
  "El Favorito":     "The Favourite",
  "Para Compartir":  "To Share",
  "Møs Vendido":     "Best Seller",
  "Møs Pedido":      "Most Ordered",
  "Fresco & Ligero": "Fresh & Light",
  "Firma del Chef":  "Chef's Signature",
  "Del Chef":        "Chef's Special",
  "Del Mar":         "From the Sea",
  "Cløsico":         "Classic",
  "Favorito":        "Favourite",
  "Exclusivo":       "Exclusive",
  "Vegano":          "Vegan",
  "Vegetariano":     "Vegetarian",
  "Para 2":          "For 2",
  "Para 4":          "For 4",
  "Para 2-3":        "For 2-3",
  "Para 4-6":        "For 4-6",
  "Picante":         "Spicy",
  "Futo":            "Futo",
};

export const categories = [
  { id: "all", label: "Todos" },
  { id: "snacks", label: "Snacks & Entradas" },
  { id: "ceviches", label: "Ceviches" },
  { id: "tacos", label: "Tacos & Garnachas" },
  { id: "flautas", label: "Flautas" },
  { id: "sushi", label: "Del Sushi Bar" },
  { id: "principales", label: "Principales" },
  { id: "postres", label: "Postres" },
];

export const sushiCategories = [
  { id: "all",              label: "Todos" },
  { id: "klassisk-nigiri",  label: "Klassisk Nigiri" },
  { id: "spesial-nigiri",   label: "Spesial Nigiri" },
  { id: "klassisk-maki",    label: "Klassisk Maki" },
  { id: "spesial-maki",     label: "Spesial Maki" },
  { id: "futo-maki",        label: "Futo Maki" },
  { id: "klassisk-sashimi", label: "Klassisk Sashimi" },
  { id: "spesial-sashimi",  label: "Spesial Sashimi" },
  { id: "tartar",           label: "Tartar" },
  { id: "combos",           label: "Combos" },
];

const _menuItems: MenuItem[] = [
  // SNACKS
  {
    id: "guacamole",
    name: "Guacamole Cløsico",
    nameEn: "Classic Guacamole",
    descriptionEn: "Avocado ripened to order, fresh lime, garlic and coriander. Topped with olive oil and pomegranate seeds. Served with artisan tostadas.",
    description: "Aguacate madurado al momento, lima fresca, ajo y cilantro. Coronado con aceite de oliva y granada. Con tostadas artesanales.",
    price: 189,
    category: "snacks",
    badge: "El Favorito",
    badgeColor: "gold",
    allergens: "Sl",
    emoji: "??",
    image: "https://images.unsplash.com/photo-1688297025825-a67dc7d4f4b6?w=800&q=80",
    vegetarian: true,
  },
  {
    id: "salsa-tasting",
    name: "Salsa Tasting",
    descriptionEn: "Trio of salsas: green tomatillo, tropical mango habanero and roasted red. A perfect introduction to the Mexican soul.",
    description: "Trøo de salsas: tomatillo verde, mango habanero tropical y roja asada. Una introducciøn perfecta al alma mexicana.",
    price: 159,
    category: "snacks",
    badge: "Para Compartir",
    badgeColor: "wasabi",
    allergens: "Sl",
    emoji: "🌶️",
    image: "https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?w=800&q=80",
    vegetarian: true,
  },
  {
    id: "nachos",
    name: "Cheddar Nachos",
    descriptionEn: "Artisan corn nachos, melted cheddar, beans, guacamole, pickled jalapeños and fresh pico de gallo.",
    description: "Nachos de maøz artesanales, cheddar fundido, frijoles, guacamole, jalapeños encurtidos y pico de gallo fresco.",
    price: 229,
    category: "snacks",
    badge: "Møs Vendido",
    badgeColor: "gold",
    allergens: "M, Sl, Su",
    emoji: "🧀",
    image: "https://images.unsplash.com/photo-1582169296194-e4d644c48063?w=800&q=80",
    vegetarian: true,
  },
  {
    id: "bean-dip",
    name: "Ranchero Bean Dip",
    nameEn: "Ranchero Bean Dip",
    descriptionEn: "Creamy white bean dip with fresh onion, garlic, coriander and red pepper. Deep flavour with artisan chips.",
    description: "Dip cremoso de alubias con cebolla fresca, ajo, cilantro y pimiento rojo. Sabor profundo con chips artesanales.",
    price: 139,
    category: "snacks",
    allergens: "Sl",
    emoji: "🫘",
    image: "https://images.unsplash.com/photo-1628294895950-9805252327bc?w=800&q=80",
    vegetarian: true,
  },
  // CEVICHES
  {
    id: "gambas-lima",
    name: "Gambas de Lima",
    nameEn: "Lima Prawns",
    descriptionEn: "Argentine king prawns marinated in tiger's milk with ginger and coriander. With tomato, avocado and cucumber on crispy tostadas.",
    description: "Langostinos argentinos marinados en leche de tigre con jengibre y cilantro. Con tomate, aguacate y pepino en tostadas crujientes.",
    price: 239,
    category: "ceviches",
    badge: "Fresco & Ligero",
    badgeColor: "wasabi",
    allergens: "Sl, Sk",
    emoji: "🦐",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80",
  },
  {
    id: "nikkei-ceviche",
    name: "Nikkei Ceviche",
    nameEn: "Nikkei Ceviche",
    descriptionEn: "The perfect fusion: ahi tuna in a Peruvian-Japanese base with avocado, daikon and citrus-soy dressing. With wasabi rice cracker.",
    description: "La fusiøn perfecta: atøn en base peruano-japonesa con aguacate, daikon y aderezo de cøtricos y soja. Con crujiente de arroz al wasabi.",
    price: 269,
    category: "ceviches",
    badge: "Firma del Chef",
    badgeColor: "gold",
    allergens: "F, Se, So, Su, Sl",
    emoji: "🐟",
    image: "https://images.unsplash.com/photo-1534482421-64566f976cfa?w=800&q=80",
  },
  // TACOS
  {
    id: "taco-pastor",
    name: "Taco de Pastor",
    nameEn: "Pastor Taco",
    descriptionEn: "Chicken marinated in achiote with pineapple and pico de gallo on a corn tortilla. A classic Mexican dish elevated.",
    description: "Pollo marinado en achiote con piøa y pico de gallo en tortilla de maøz. Un cløsico mexicano elevado.",
    price: 199,
    category: "tacos",
    allergens: "Sl, Su",
    emoji: "🌮",
    image: "https://images.unsplash.com/photo-1570461226513-e08b58a52c53?w=800&q=80",
    halal: true,
  },
  {
    id: "taco-gambas",
    name: "Taco de Gambas",
    nameEn: "Prawn Taco",
    descriptionEn: "Golden tempura Nobashi scampi with pickled red cabbage, trout roe and chipotle-chili mayonnaise.",
    description: "Scampi Nobashi en tempura dorado con col roja encurtida, huevas de trucha y mayonesa chipotle-chili.",
    price: 189,
    category: "tacos",
    badge: "Møs Pedido",
    badgeColor: "gold",
    allergens: "H, F, Sk, Su, E",
    emoji: "🍤",
    image: "https://images.unsplash.com/photo-1604467794349-0b74285de7e7?w=800&q=80",
  },
  {
    id: "taco-pescado",
    name: "Taco de Pescado",
    nameEn: "Fish Taco",
    descriptionEn: "Crispy fried fish with fresh coleslaw, trout roe and coriander, chili and cheese sauce.",
    description: "Pescado crujiente frito con coleslaw fresca, huevas de trucha y salsa de cilantro, chili y queso.",
    price: 189,
    category: "tacos",
    allergens: "H, M, F, E, Sn",
    emoji: "🐠",
    image: "https://images.unsplash.com/photo-1512838243191-e81168b2e0ad?w=800&q=80",
  },
  {
    id: "taco-cerdo",
    name: "Tacos de Cerdo",
    nameEn: "Pork Tacos",
    descriptionEn: "Shredded pork in smoky chili and honey sauce, with guacamole and pico de gallo.",
    description: "Cerdo deshilachado en salsa de chili ahumado y miel, con guacamole y pico de gallo.",
    price: 199,
    category: "tacos",
    allergens: "So, Su, Sn",
    emoji: "🥩",
    image: "https://images.unsplash.com/photo-1611250188496-e966043a0629?w=800&q=80",
  },
  {
    id: "quesabirrias",
    name: "Quesabirrias",
    nameEn: "Quesabirrias",
    descriptionEn: "Slow-cooked brisket in Mexican adobo, in a melted-cheese taco with consommø for dipping. The ultimate experience.",
    description: "Brisket cocido a fuego lento en adobo mexicano, en taco de queso fundido con consomø para mojar. La experiencia definitiva.",
    price: 289,
    category: "tacos",
    badge: "Signature",
    badgeColor: "gold",
    allergens: "M, Sl, So",
    emoji: "🫕",
    halal: true,
    image: "https://images.unsplash.com/photo-1613514785940-daed07799d9b?w=800&q=80",
  },
  {
    id: "costra-pastor",
    name: "Costra de Pastor",
    nameEn: "Pastor Cheese Crust",
    descriptionEn: "Pastor chicken with coriander, onion and fresh pineapple in a golden cheese crust.",
    description: "Pollo pastor con cilantro, cebolla y piøa fresca en costra de queso dorado.",
    price: 279,
    category: "tacos",
    allergens: "M, Sl, Su",
    emoji: "🌯",
    image: "https://images.unsplash.com/photo-1553909489-cd47e0907980?w=800&q=80",
    halal: true,
  },
  // FLAUTAS
  {
    id: "flauta-res",
    name: "Flautas de Res",
    nameEn: "Beef Flautas",
    descriptionEn: "Crispy beef taco with red salsa, sour cream, halloumi and beetroot mayonnaise.",
    description: "Taco crujiente de ternera con salsa roja, crema agria, halloumi y mayonesa de remolacha.",
    price: 267,
    category: "flautas",
    allergens: "M, E, Sl",
    emoji: "🥙",
    image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?w=800&q=80",
  },
  {
    id: "flauta-camote",
    name: "Flautas de Camote",
    nameEn: "Sweet Potato Flautas",
    descriptionEn: "Crispy sweet potato with mango habanero, sour cream, halloumi and chipotle mayo.",
    description: "Boniato crujiente con mango habanero, crema agria, halloumi y chipotle mayo.",
    price: 259,
    category: "flautas",
    badge: "Vegetariano",
    badgeColor: "wasabi",
    allergens: "M, E",
    emoji: "🍠",
    image: "https://images.unsplash.com/photo-1625944525533-473f1a3d54e7?w=800&q=80",
    vegetarian: true,
  },
  {
    id: "flauta-pato",
    name: "Flautas de Pato",
    nameEn: "Duck Flautas",
    descriptionEn: "Shredded duck with chocolate and chili mole poblano, sour cream and red cabbage.",
    description: "Pato deshilachado con mole poblano de chocolate y chili, crema agria y col roja.",
    price: 269,
    category: "flautas",
    badge: "Premium",
    badgeColor: "gold",
    allergens: "Se, H, M, E, Sl, So",
    emoji: "🦆",
    image: "https://images.unsplash.com/photo-1574894709920-11b28be1ea2b?w=800&q=80",
  },
  // SUSHI
  {
    id: "laksetartar",
    name: "Laksetartar",
    descriptionEn: "Fresh salmon with avocado, mango chutney, avocado cream, salmon roe, passionfruit sauce and rice cracker.",
    description: "Salmøn fresco con aguacate, chutney de mango, crema de aguacate, huevas de salmøn, salsa de maracuyø y crujiente de arroz.",
    price: 269,
    category: "sushi",
    badge: "Best Seller",
    badgeColor: "gold",
    allergens: "G, F, So, Se",
    emoji: "🍣",
    image: "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=800&q=80",
  },
  {
    id: "truffle-akami",
    name: "Truffle Akami",
    descriptionEn: "Ahi tuna akami sashimi crowned with black truffle honey and rice cracker. Japanese elegance at its purest.",
    description: "Sashimi de atøn akami coronado con miel de trufa negra y crujiente de arroz. Elegancia japonesa en estado puro.",
    price: 269,
    category: "spesial-sashimi",
    badge: "Exclusivo",
    badgeColor: "gold",
    allergens: "G, F",
    emoji: "🫧",
    image: "https://images.unsplash.com/photo-1676037150408-4b59a542fa7c?w=800&q=80",
  },
  {
    id: "obento-sashimi",
    name: "Obento Sashimi",
    descriptionEn: "Turbot sashimi with wasabi vinaigrette, jalapeño cream, pomegranate seeds and crispy sweet potato strips.",
    description: "Sashimi de rodaballo con vinagreta de wasabi, crema de jalapeño, semillas de granada y tiras crujientes de boniato.",
    price: 269,
    category: "spesial-sashimi",
    badge: "Del Chef",
    badgeColor: "gold",
    allergens: "G, F, So, Se, Sn",
    emoji: "🐡",
    image: "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=800&q=80",
  },
  {
    id: "chefs-mix-16",
    name: "Chef's Mix 16 piezas",
    descriptionEn: "Chef's selection of 16 assorted sushi pieces. The Obento experience in sharing format.",
    description: "Selecciøn del chef de 16 piezas de sushi variado. La experiencia Obento en formato para compartir.",
    price: 465,
    category: "sushi",
    badge: "Para 2",
    badgeColor: "wasabi",
    emoji: "🍱",
    image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&q=80",
  },
  {
    id: "chefs-mix-32",
    name: "Chef's Mix 32 piezas",
    descriptionEn: "Chef's selection of 32 pieces. The Obento experience in grand format for celebrations.",
    description: "Selecciøn del chef de 32 piezas. La experiencia Obento en gran formato para celebrar.",
    price: 890,
    category: "sushi",
    badge: "Para 4",
    badgeColor: "wasabi",
    emoji: "🎌",
    image: "https://images.unsplash.com/photo-1617196034096-9a9d7a1d9ecf?w=800&q=80",
  },
  // PRINCIPALES
  {
    id: "brisket",
    name: "Brisket Norteøo",
    nameEn: "Northern Brisket",
    descriptionEn: "300g beef brisket slow-roasted for 15 hours and glazed with chimichurri. Fresh coleslaw and corn tortillas.",
    description: "300g de pecho de buey horneado 15 horas y glaseado con chimichurri. Coleslaw fresca y tortillas de maøz.",
    price: 449,
    category: "principales",
    badge: "Premium",
    badgeColor: "gold",
    allergens: "E, Su, Sn",
    emoji: "🥩",
    halal: true,
    image: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800&q=80",
  },
  {
    id: "entrecot",
    name: "Entrecot Uruguayo",
    nameEn: "Uruguayan Entrecøte",
    descriptionEn: "250g grilled Uruguayan entrecote with oven potatoes, padrøn peppers and house chimichurri.",
    description: "250g de entrecot a la parrilla con patatas al horno, pimientos padrøn y chimichurri de la casa.",
    price: 469,
    category: "principales",
    badge: "Signature",
    badgeColor: "gold",
    allergens: "Su, Sn",
    emoji: "🥩",
    halal: true,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
  },
  {
    id: "torsk",
    name: "Golden Torsk",
    descriptionEn: "Cod with coconut and prawn sauce, mashed potato and seasonal vegetables. Fresh, creamy and delicate.",
    description: "Bacalao con salsa de coco y gambas, purø de patata y verduras de temporada. Fresco, cremoso y delicado.",
    price: 379,
    category: "principales",
    badge: "Del Mar",
    badgeColor: "wasabi",
    allergens: "F, Sk, M",
    emoji: "🐟",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80",
  },
  // POSTRES
  {
    id: "churros",
    name: "Churros",
    nameEn: "Churros",
    descriptionEn: "Golden churros with dark chocolate sauce, crunchy vanilla crumble and artisan lucuma ice cream.",
    description: "Churros dorados con salsa de chocolate negro, crumble de vainilla crujiente y helado artesanal de lucuma.",
    price: 189,
    category: "postres",
    badge: "Cløsico",
    badgeColor: "gold",
    allergens: "H, M",
    emoji: "🍩",
    image: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=800&q=80",
  },
  {
    id: "brownie",
    name: "Avocado Brownie",
    nameEn: "Avocado Brownie",
    descriptionEn: "Dark chocolate and avocado brownie with pistachio ice cream and salted caramel.",
    description: "Brownie de chocolate negro con aguacate y nueces, helado de pistacho y caramelo salado.",
    price: 189,
    category: "postres",
    allergens: "E, M, H, Va, Pi",
    emoji: "🍫",
    image: "https://images.unsplash.com/photo-1564355808539-22fda35bed7e?w=800&q=80",
  },
  {
    id: "tres-leches",
    name: "Tres Leches",
    nameEn: "Tres Leches",
    descriptionEn: "Airy sponge soaked in three milks, topped with whipped cream and cocoa. A comforting classic.",
    description: "Bizcocho aireado empapado en tres leches, coronado con nata montada y cacao. Un cløsico reconfortante.",
    price: 185,
    category: "postres",
    badge: "Favorito",
    badgeColor: "gold",
    allergens: "M, H, E",
    emoji: "🎂",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&q=80",
  },
  {
    id: "sorbet",
    name: "Passion Mango Sorbet",
    nameEn: "Passion Mango Sorbet",
    descriptionEn: "Artisan passionfruit and mango sorbet with vegan gluten-free crumble. Refreshing and elegant.",
    description: "Sorbete artesanal de maracuyø y mango con crumble vegano y sin gluten. Refrescante y elegante.",
    price: 159,
    category: "postres",
    badge: "Vegano",
    badgeColor: "wasabi",
    emoji: "🍧",
    image: "https://images.unsplash.com/photo-1488900128323-21503983a07e?w=800&q=80",
    vegetarian: true,
  },
];

const _sushiMenuItems: MenuItem[] = [
  // -- KLASSISK NIGIRI (4 stk) --
  { id: "nigiri-laks",          name: "Nigiri Laks",          description: "Klassisk laksenigiri (4 stk).",          descriptionEn: "Classic salmon nigiri (4 pcs.)",       price: 159, category: "klassisk-nigiri",  allergens: "F",                        emoji: "\u{1F363}", image: "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=800&q=80" },
  { id: "nigiri-tunfisk-akami", name: "Nigiri Tunfisk Akami", description: "Klassisk tunfisk akami nigiri (4 stk).", descriptionEn: "Classic akami tuna nigiri (4 pcs.)",   price: 189, category: "klassisk-nigiri",  allergens: "F",                        emoji: "\u{1F363}", image: "https://images.unsplash.com/photo-1617196034096-9a9d7a1d9ecf?w=800&q=80" },
  { id: "nigiri-bonito",        name: "Nigiri Bonito",        description: "Klassisk bonito nigiri (4 stk).",        descriptionEn: "Classic bonito nigiri (4 pcs.)",        price: 169, category: "klassisk-nigiri",  allergens: "F",                        emoji: "\u{1F363}", image: "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=800&q=80" },
  { id: "nigiri-kveite",        name: "Nigiri Kveite",        description: "Klassisk kveitenigi (4 stk).",           descriptionEn: "Classic halibut nigiri (4 pcs.)",       price: 169, category: "klassisk-nigiri",  allergens: "F",                        emoji: "\u{1F363}", image: "https://images.unsplash.com/photo-1563612116625-3012372fccce?w=800&q=80" },
  { id: "nigiri-hamachi",       name: "Nigiri Hamachi",       description: "Klassisk hamachi nigiri (4 stk).",       descriptionEn: "Classic hamachi nigiri (4 pcs.)",       price: 189, category: "klassisk-nigiri",  allergens: "F",                        emoji: "\u{1F363}", image: "https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=800&q=80" },
  { id: "nigiri-kamskjell",     name: "Nigiri Kamskjell",     description: "Klassisk kamskjell nigiri (4 stk).",     descriptionEn: "Classic scallop nigiri (4 pcs.)",       price: 139, category: "klassisk-nigiri",  allergens: "Bl",                       emoji: "\u{1F363}", image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&q=80" },
  // -- SPESIAL NIGIRI (4 stk) --
  { id: "aburi-sake",   name: "Aburi Sake",   description: "Flambert laksenigiri toppet med husets majones og purre.", descriptionEn: "Flame-seared salmon nigiri topped with house mayonnaise and chives.",    price: 179, category: "spesial-nigiri", allergens: "F, E, So",  emoji: "\u{1F525}", badge: "Spesial", badgeEn: "Special", badgeColor: "gold",   image: "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=800&q=80" },
  { id: "troffel-toro", name: "Trøffel Toro", description: "Flambert toro-nigiri med trøffelmajones.",      descriptionEn: "Flame-seared toro nigiri with truffle mayonnaise.",                       price: 199, category: "spesial-nigiri", allergens: "F, E, So",  emoji: "\u{1FAB7}", badge: "Spesial", badgeEn: "Special", badgeColor: "gold",   image: "https://images.unsplash.com/photo-1676037150408-4b59a542fa7c?w=800&q=80" },
  { id: "hirame",       name: "Hirame",       description: "Flambert kveitenigiri med tamarindsaus og wasabi.",       descriptionEn: "Flame-seared halibut nigiri with tamarind sauce and wasabi.",             price: 189, category: "spesial-nigiri", allergens: "F, So, Se", emoji: "\u{1F421}", badge: "Spesial", badgeEn: "Special", badgeColor: "gold",   image: "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=800&q=80" },
  // -- KLASSISK MAKI (8 stk) --
  { id: "laks-maki",         name: "Laks Maki",         description: "Maki fylt med laks og purre (8 stk).",                                             descriptionEn: "Maki filled with salmon and chives (8 pcs.)",                                                   price: 199, category: "klassisk-maki", allergens: "F",            emoji: "\u{1F300}", image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&q=80" },
  { id: "obento-tempura-maki", name: "Obento Tempura Maki", description: "Maki fylt med tempura scampi og avokado, toppet med avokadokrem (8 stk).",         descriptionEn: "Maki filled with tempura scampi and avocado, topped with avocado cream (8 pcs.)",              price: 199, category: "klassisk-maki", allergens: "G, F, So, Se", emoji: "\u{1F300}", image: "https://images.unsplash.com/photo-1617196034096-9a9d7a1d9ecf?w=800&q=80" },
  { id: "kanskjell-maki",    name: "Kanskjell Maki",    description: "Maki fylt med agurk og kamskjell med wasabi-vinaigrette, toppet med ikura (8 stk).",descriptionEn: "Maki filled with cucumber and scallop with wasabi vinaigrette, topped with ikura (8 pcs.)",   price: 209, category: "klassisk-maki", allergens: "So, Se, Bl",   emoji: "\u{1F300}", image: "https://images.unsplash.com/photo-1562802378-063ec186a863?w=800&q=80" },
  { id: "california-maki",   name: "California Maki",   description: "Maki fylt med krabbe, avokado og kremost (8 stk).",                                descriptionEn: "Maki filled with crab, avocado and cream cheese (8 pcs.)",                                     price: 209, category: "klassisk-maki", allergens: "G, Sk, F",     emoji: "\u{1F300}", image: "https://images.unsplash.com/photo-1593843596379-9f3e2d7e7b25?w=800&q=80" },
  { id: "tunfisk-maki",      name: "Tunfisk Maki",      description: "Maki fylt med tunfisk og avokado (8 stk).",                                        descriptionEn: "Maki filled with tuna and avocado (8 pcs.)",                                                    price: 209, category: "klassisk-maki", allergens: "F",            emoji: "\u{1F300}", image: "https://images.unsplash.com/photo-1617196034099-b65b41537d12?w=800&q=80" },
  // -- SPESIAL MAKI (8 stk) --
  { id: "px-maki",      name: "PX Maki",      description: "Maki fylt med tempura scampi, sterk laksetartar og PX-saus. Toppet med mango-smør og rogn (8 stk).", descriptionEn: "Maki filled with tempura scampi, spicy salmon tartar and PX sauce. Topped with mango butter and roe (8 pcs.)", price: 225, category: "spesial-maki", allergens: "G, Sk, F, So, M, Se, Sn, Su", emoji: "?", badge: "Signature",             badgeColor: "gold",   image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&q=80" },
  { id: "kiwami",       name: "Kiwami",       description: "Maki fylt med purre og sesongens hvite fisk, toppet med tunfisk og trøffelsaus (8 stk).", descriptionEn: "Maki filled with chives and seasonal white fish, topped with tuna and truffle sauce (8 pcs.)",      price: 239, category: "spesial-maki", allergens: "F, So",                        emoji: "\u{1F300}", badge: "Spesial", badgeEn: "Special", badgeColor: "gold",   image: "https://images.unsplash.com/photo-1676037150408-4b59a542fa7c?w=800&q=80" },
  { id: "spicy-maguro", name: "Spicy Maguro", description: "Maki fylt med agurk og avokado, toppet med spicy tunfisk tartar og søtpotetstrimler (8 stk).",   descriptionEn: "Maki filled with cucumber and avocado, topped with spicy tuna tartar and sweet potato strips (8 pcs.)", price: 229, category: "spesial-maki", allergens: "G, F, So, Se, Su",             emoji: "\u{1F525}", badge: "Picante", badgeEn: "Spicy",   badgeColor: "wasabi", image: "https://images.unsplash.com/photo-1617196034099-b65b41537d12?w=800&q=80" },
  { id: "hotate-maki",  name: "Hotate Maki",  description: "Maki fylt med agurk og avokado, toppet med flambert kamskjell og jalapeñokrem (8 stk).",          descriptionEn: "Maki filled with cucumber and avocado, topped with flame-seared scallop and jalapeño cream (8 pcs.)", price: 229, category: "spesial-maki", allergens: "So, Se, Bl",                    emoji: "\u{1F300}",                                             image: "https://images.unsplash.com/photo-1562802378-063ec186a863?w=800&q=80" },
  // -- FUTO MAKI (6 stk) --
  { id: "yuzu-tempura-scampi", name: "Yuzu Tempura Scampi", description: "Futo maki fylt med purre, avokado, dobbel tempura scampi, yuzumajones og shichimi togarashi (6 stk).", descriptionEn: "Futo maki filled with chives, avocado, double tempura scampi, yuzu mayonnaise and shichimi togarashi (6 pcs.)", price: 239, category: "futo-maki", allergens: "G, Sk, E, F, So, M, Se, Sn", emoji: "\u{1F300}", badge: "Futo", badgeColor: "gold", image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&q=80" },
  // -- KLASSISK SASHIMI (4 stk) --
  { id: "sashimi-laks",          name: "Sashimi Laks",          description: "Klassisk laksesashimi (4 stk).",          descriptionEn: "Classic salmon sashimi (4 pcs.)",       price: 139, category: "klassisk-sashimi", allergens: "F",  emoji: "\u{1F420}", image: "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=800&q=80" },
  { id: "sashimi-tunfisk-akami", name: "Sashimi Tunfisk Akami", description: "Klassisk tunfisk akami sashimi (4 stk).", descriptionEn: "Classic akami tuna sashimi (4 pcs.)",   price: 179, category: "klassisk-sashimi", allergens: "F",  emoji: "\u{1F420}", image: "https://images.unsplash.com/photo-1676037150408-4b59a542fa7c?w=800&q=80" },
  { id: "sashimi-bonito",        name: "Sashimi Bonito",        description: "Klassisk bonito sashimi (4 stk).",        descriptionEn: "Classic bonito sashimi (4 pcs.)",       price: 159, category: "klassisk-sashimi", allergens: "F",  emoji: "\u{1F420}", image: "https://images.unsplash.com/photo-1617196034096-9a9d7a1d9ecf?w=800&q=80" },
  { id: "sashimi-kveite",        name: "Sashimi Kveite",        description: "Klassisk kveitesashimi (4 stk).",         descriptionEn: "Classic halibut sashimi (4 pcs.)",      price: 159, category: "klassisk-sashimi", allergens: "F",  emoji: "\u{1F420}", image: "https://images.unsplash.com/photo-1563612116625-3012372fccce?w=800&q=80" },
  { id: "sashimi-hamachi",       name: "Sashimi Hamachi",       description: "Klassisk hamachi sashimi (4 stk).",       descriptionEn: "Classic hamachi sashimi (4 pcs.)",      price: 179, category: "klassisk-sashimi", allergens: "F",  emoji: "\u{1F420}", image: "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=800&q=80" },
  { id: "sashimi-kamskjell",     name: "Sashimi Kamskjell",     description: "Klassisk kamskjell sashimi (4 stk).",     descriptionEn: "Classic scallop sashimi (4 pcs.)",      price: 159, category: "klassisk-sashimi", allergens: "Bl", emoji: "\u{1F420}", image: "https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=800&q=80" },
  // -- SPESIAL SASHIMI (4 stk) --
  { id: "umai-sashimi",  name: "Umai Sashimi",  description: "Laksesashimi toppet med mangsmør, ponzu, jalapeño og rogn (4 stk).",                                     descriptionEn: "Salmon sashimi topped with mango butter, ponzu, jalapeño and roe (4 pcs.)",                                               price: 239, category: "spesial-sashimi", allergens: "F, So, M, Se, Sn", emoji: "\u{1F420}", badge: "Spesial", badgeEn: "Special",         badgeColor: "gold", image: "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=800&q=80" },
  { id: "truffle-akami", name: "Truffle Akami", description: "Tunfisk akami sashimi toppet med trøffelhonning og riskjeks (4 stk).",                                         descriptionEn: "Akami tuna sashimi topped with truffle honey and rice cracker (4 pcs.)",                                                          price: 269, category: "spesial-sashimi", allergens: "G, F",             emoji: "\u{1FAB7}", badge: "Exclusivo", badgeEn: "Exclusive",     badgeColor: "gold", image: "https://images.unsplash.com/photo-1676037150408-4b59a542fa7c?w=800&q=80" },
  { id: "obento-sashimi",  name: "Obento Sashimi",  description: "Kveitesashimi toppet med wasabi-vinaigrette, jalapeñokrem, granateplefrø og sprø søtpotettrøder (4 stk).", descriptionEn: "Halibut sashimi topped with wasabi vinaigrette, jalapeño cream, pomegranate seeds and crispy sweet potato strips (4 pcs.)", price: 269, category: "spesial-sashimi", allergens: "G, F, So, Se, Sn",  emoji: "\u{1F421}", badge: "Del Chef", badgeEn: "Chef\'s Special", badgeColor: "gold", image: "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=800&q=80" },
  // -- TARTAR --
  { id: "laksetartar", name: "Laksetartar", description: "Laks med avokado, mango chutney, avokadokrem, lakserogn, pasjonsfuktsaus og riskjeks.", descriptionEn: "Salmon with avocado, mango chutney, avocado cream, salmon roe, passion fruit sauce and rice cracker.", price: 269, category: "tartar", allergens: "G, F, So, Se", emoji: "\u{1F363}", badge: "Best Seller", badgeColor: "gold", image: "https://images.unsplash.com/photo-1535400255456-984b8c7b0db5?w=800&q=80" },
  // -- COMBOS --
  { id: "moriawase-16",    name: "Moriawase 16 stk",    description: "Blandet sashimifat servert på is. 4 typer av sesongens fisk (16 stk).", descriptionEn: "Assorted sashimi platter served on ice. 4 types of seasonal fish (16 pcs.)", price: 1150, category: "combos", emoji: "\u{1F381}", badge: "Para 2-3", badgeEn: "For 2-3", badgeColor: "wasabi", image: "https://images.unsplash.com/photo-1617196034096-9a9d7a1d9ecf?w=800&q=80" },
  { id: "moriawase-32",    name: "Moriawase 32 stk",    description: "Blandet sashimifat servert på is. 4 typer av sesongens fisk (32 stk).", descriptionEn: "Assorted sashimi platter served on ice. 4 types of seasonal fish (32 pcs.)", price: 2200, category: "combos", emoji: "\u{1F38C}", badge: "Para 4-6", badgeEn: "For 4-6", badgeColor: "wasabi", image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&q=80" },
  { id: "kokkens-valg-16", name: "Kokkens Valg 16 pcs", description: "Mixed Sushi Combos seleccionados por el chef (16 pcs).",               descriptionEn: "Chef\'s selection of mixed sushi combos (16 pcs.)",  price:  465, category: "combos", emoji: "\u{1F371}", badge: "Para 2", badgeEn: "For 2", badgeColor: "gold",   image: "https://images.unsplash.com/photo-1617196034099-b65b41537d12?w=800&q=80" },
  { id: "kokkens-valg-32", name: "Kokkens Valg 32 pcs", description: "Mixed Sushi Combos seleccionados por el chef (32 pcs).",               descriptionEn: "Chef\'s selection of mixed sushi combos (32 pcs.)", price:  890, category: "combos", emoji: "\u{1F38C}", badge: "Para 4", badgeEn: "For 4", badgeColor: "wasabi", image: "https://images.unsplash.com/photo-1562802378-063ec186a863?w=800&q=80" },
];

export const menuItems: MenuItem[]      = _menuItems.map(i => ({ ...i, concepto: "mexican" as const }));
export const sushiMenuItems: MenuItem[] = _sushiMenuItems.map(i => ({ ...i, concepto: "sushi" as const }));

